packages:
  - name: default
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      MAX_DAILY_COST: "5"
      NODE_ENV: "production"
    functions:
      - name: test
        runtime: nodejs:default
        web: true

      - name: analyze-form
        runtime: nodejs:default
        web: true

      - name: chat
        runtime: nodejs:default
        web: true

      - name: rag-query
        runtime: nodejs:default
        web: true
