packages:
  - name: default
    functions:
      - name: analyze-form
        runtime: nodejs:default
        web: true

      - name: chat
        runtime: nodejs:default
        web: true

      - name: rag-query
        runtime: nodejs:default
        web: true
